version: "3.8"

services:
  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      [
        "sh",
        "-c",
        "echo $DB_USERNAME && echo $DB_PASSWORD && echo $DB_NAME && postgres",
      ]
volumes:
  pgdata:
