version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: database
      REACT_APP_APIKEY: ${REACT_APP_APIKEY}
      JWT_SECRET_ACCESS_KEY: ${JWT_SECRET_ACCESS_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

volumes:
  pgdata:
